apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bambuddy-data
  namespace: bambuddy
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bambuddy-logs
  namespace: bambuddy
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
